/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeistungenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leistungen': typeof LeistungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/leistungen'
    | '/sitemap.xml'
    | '/leistungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/sitemap.xml'
    | '/leistungen'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/leistungen'
    | '/sitemap.xml'
    | '/leistungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GalerieRoute: typeof GalerieRoute
  ImpressumRoute: typeof ImpressumRoute
  LeistungenRoute: typeof LeistungenRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof LeistungenRoute
    }
  }
}

interface LeistungenRouteChildren {
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenIndexRoute: LeistungenIndexRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  GalerieRoute: GalerieRoute,
  ImpressumRoute: ImpressumRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
